### ISSUE TITLE
Note about max length

### ISSUE THREAD

**Issue by do-me** [lucasnewman/f5-tts-mlx#10]
Hi thanks for converting to MLX! 

Running text longer than 2 sentences gives:
- a long white noise in the beginning
- a general higher reading speed 
- gibberish outputs. Ironically, the generated audio imitates someone actually struggling with reading the text lol. 

```bash
python -m f5_tts_mlx.generate --text "An information silo, or a group of such silos, is an insular management system in which one information system or subsystem is incapable of reciprocal operation with others that are, or should be, related. Thus information is not adequately shared but rather remains sequestered within each system or subsystem, figuratively trapped within a container like grain is trapped within a silo: there may be much of it, and it may be stacked quite high and freely available within those limits, but it has no effect outside those limits. Such data silos are proving to be an obstacle for businesses wishing to use data mining to make productive use of their data."
```
[output.wav.zip](https://github.com/user-attachments/files/17456393/output.wav.zip)

What's the maximum recommended length?

**Comment by lucasnewman** [comment]
The model was trained for <40s outputs, so that's the effective cap per generation. I would guess the duration estimation is pretty rough here -- you may want to go sentence by sentence in a loop and stitch it back together for more natural-sounding speech.

**Comment by lucasnewman** [comment]
I wired in a duration predictor which may help. You may need to adjust the speed of generation based on your reference audio sample — lmk how it goes! 🚀
