### ISSUE TITLE
How to install correctly?

### ISSUE THREAD

**Issue by gablucas** [lucasnewman/f5-tts-mlx#11]
- Downloaded the code
- python -m venv venv
- venv\Scripts\activate
- pip install f5-tts-mlx
- pip install -r requirements.txt

And i receive this error
ERROR: Could not find a version that satisfies the requirement mlx (from versions: none)
ERROR: No matching distribution found for mlx

Are there other things I should do? Should I add this code inside the original T5 TTS?

**Comment by lucasnewman** [comment]
Are you using a computer with an Apple Silicon chip, i.e. a Mac? If not, you should probably use the pytorch repository.

**Comment by MrFaru-pixel** [comment]
Try this instead:

- [...]
- pip install "git+https://github.com/ml-explore/mlx" # slow but **pip install mlx** fails currently; has nothing to do with f5-tts-mlx
- pip install f5-tts-mlx==0.1.2 # the last version working well for me; no time to investigate

**Comment by Akossimon** [comment]
i also am wondering how to install this on my mac mini M2 Pro..  can Pinokio install this for me , would You know anything about that , by any chance?

**Comment by yodahuang** [comment]
Just add my 2 cents: the normal method is working of me, using [uv](https://docs.astral.sh/uv/) to do the version resolution.

**Comment by kylehowells** [comment]
Providing you are on an M chip Mac.

```bash
python3.10 -m venv venv
```

I've found most ML/AI stuff doesn't work on anything higher than python 3.10

**Comment by yodahuang** [comment]
I've verified it works as expected on CPython 3.12. See https://github.com/yodahuang/bookpurr
