### ISSUE TITLE
Two almost identical version of `generate.py`

### ISSUE THREAD

**Issue by yodahuang** [lucasnewman/f5-tts-mlx#12]
There's one in `example`, and a one in the library itself. From commit history it seems we have the example version first and the changes are then applied to both version. 

Is it intentional to have two versions of almost exactly the same code? (They are only different in formatting, with one have `,` after `seed=seed`).

It would also be useful to mention as a Python library, you can call `from f5_tts_mlx.generate import generate`, since from the current readme, it's natural to think one need to re-implement all that's shown in `example/generate.py`.

**Comment by lucasnewman** [comment]
Yep, fair, I'll clean that up, thanks.
