### ISSUE TITLE
Error generating audio

### ISSUE THREAD

**Issue by maiqingqiang** [lucasnewman/f5-tts-mlx#13]
It seems that f5-tts-mlx does not support certain characters, resulting in a negative value for seq_len - text_len. I haven't figured out exactly which characters they are yet.

## Error
```log
ValueError: Invalid high padding size (-185) passed to pad for axis 1. Padding sizes must be non-negative
```
![image](https://github.com/user-attachments/assets/f237d78d-892d-4818-b31c-adea66549385)

https://x.com/Know1Thyself/status/1851427661597589541

https://github.com/maiqingqiang/NotebookMLX/issues/1

**Comment by lucasnewman** [comment]
Do you have an example of an input string that fails?

**Comment by maiqingqiang** [comment]
> Do you have an example of an input string that fails?

```python
from f5_tts_mlx.generate import generate

generate(
    generation_text="""
Alright, folks, welcome to the podcast where we dive deep into the fascinating world of knowledge distillation in large language models, or LLMs for short. If you're here, you're likely curious about how these powerful AI tools can be made more accessible and effective for everyone. Today, we're going to peel back the layers and see how knowledge distillation works, and why it's such a game-changer. I’m your host, and I've got some incredible stories to share. So grab your coffee, get comfy, and let's jump into this episode where we talk about transforming complex AI capabilities into more manageable and accessible forms.
""",
    model_name="lucasnewman/f5-tts-mlx",
)
```

**Comment by lucasnewman** [comment]
Thanks! I put in a fix you can get if you do `pip install -U f5-tts-mlx`

**Comment by maiqingqiang** [comment]
Thanks! @lucasnewman

**Comment by hfyydd** [comment]
![WX20241104-120717](https://github.com/user-attachments/assets/a66289f0-5e33-40ff-9d56-72f73aa641a7)
![WX20241104-120546@2x](https://github.com/user-attachments/assets/c6530c9e-d8f7-4913-b793-239b103a8960)

**Comment by hfyydd** [comment]
`from f5_tts_mlx.generate import generate
MODEL = "lucasnewman/f5-tts-mlx"

text = """
[
    ("Speaker 1", "欢迎来到今天的播客，我们将深入探讨信息学奥林匹克竞赛大纲，了解计算机科学的世界。这个大纲是为全国青少年信息学奥林匹克竞赛和中国计算机学会主办的其他相关活动而制定的。"),
    ("Speaker 2", "哇，听起来很厉害！我从来没有听说过信息学奥林匹克竞赛大纲。能不能给我介绍一下这个大纲的结构和内容吗？"),
    ("Speaker 1", "当然！大纲分为四部分：基础知识与编程环境、C++程序设计、数据结构、算法和数学与其他。每一部分都涵盖了从入门级到高级的知识点。"),
    ("Speaker 2", "嗯，那么基础知识与编程环境部分包括什么呢？"),
    ("Speaker 1", "啊，这部分包括计算机的基本构成、Windows和Linux等操作系统的基本概念、计算机网络和Internet的基本概念等。这些知识点是计算机科学的基础，理解这些概念对于后续的学习非常重要。"),
    ("Speaker 2", "哈，我记得小时候第一次使用电脑的时候，完全不知道怎么操作。现在看来，这些基础知识确实很重要。"),
    ("Speaker 1", "是的！基础知识是计算机科学的基础。下一部分是C++程序设计。这部分包括C++的基本概念、语句、运算、数组和字符串的处理等。"),
    ("Speaker 2", "[叹气] C++听起来很难！我从来没有学过C++。能不能给我介绍一下C++的基本概念吗？"),
    ("Speaker 1", "当然！C++是一种面向对象的程序设计语言。它的基本概念包括标识符、关键字、常量、变量、字符串等。这些概念是C++的基础，理解这些概念对于后续的学习非常重要。"),
    ("Speaker 2", "嗯，我开始理解了。那么数据结构部分包括什么呢？"),
    ("Speaker 1", "啊，这部分包括线性结构、树结构、图结构等。这些数据结构是计算机科学的基础，理解这些结构对于后续的学习非常重要。"),
    ("Speaker 2", "[笑] 哈，我记得小时候学过树结构和图结构。这些结构确实很有趣。"),
    ("Speaker 1", "是的！数据结构是计算机科学的基础。下一部分是算法。这部分包括算法的概念、描述、入门算法、基础算法等。"),
    ("Speaker 2", "啊，算法听起来很难！我从来没有学过算法。能不能给我介绍一下算法的概念吗？"),
    ("Speaker 1", "当然！算法是一种解决问题的方法。它包括算法的概念、描述、入门算法、基础算法等。这些知识点是计算机科学的基础，理解这些概念对于后续的学习非常重要。"),
    ("Speaker 2", "嗯，我开始理解了。那么数学与其他部分包括什么呢？"),
    ("Speaker 1", "啊，这部分包括数及其运算、初等数学、初等数论、离散与组合数学、线性代数等。这些数学知识点是计算机科学的基础，理解这些概念对于后续的学习非常重要。"),
    ("Speaker 2", "哈，我记得小时候学过这些数学知识点。这些知识点确实很有趣。"),
    ("Speaker 1", "是的！数学与其他是计算机科学的基础。最后，我们来总结一下今天的内容。信息学奥林匹克竞赛大纲涵盖了从入门级到高级的计算机科学知识，包括基础知识、C++程序设计、数据结构、算法和数学与其他。"),
    ("Speaker 2", "嗯，我理解了。感谢您的解释！"),
    ("Speaker 1", "不客气！希望今天的播客能帮助大家理解信息学奥林匹克竞赛大纲。"),
    ("Speaker 2", "[叹气] 感谢您的收听！如果您有任何问题或想法，请在评论中留言。我们将在下一期播客中见到您！")
]
"""

if __name__ == "__main__":
    generate(
        generation_text=text,
        model_name=MODEL
    )`
