### ISSUE TITLE
First try running f5-tts-mlx

### ISSUE THREAD

**Issue by ahmetkca** [lucasnewman/f5-tts-mlx#2]
I have installed `f5-tts-mlx` but I got couple of no module found errors for `mlx` and `numpy` I then installed them to but now I get this `einops` module not found error. I was just wondering if I am running the example/generate.py wrong?

```
❯ pip freeze
f5-tts-mlx==0.0.2
mlx==0.18.1
numpy==2.1.2
setuptools==75.1.0
```

Error:
```
❯ python -m generate
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/ahmetkca/Projects/f5-tts-mlx/f5-tts-mlx/examples/generate.py", line 10, in <module>
    from f5_tts_mlx.cfm import CFM
  File "/Users/ahmetkca/Projects/f5-tts-mlx/.direnv/python-3.12/lib/python3.12/site-packages/f5_tts_mlx/cfm.py", line 18, in <module>
    from einops.array_api import rearrange, reduce, repeat
ModuleNotFoundError: No module named 'einops'
```

**Comment by ahmetkca** [comment]
I thought all the required dependencies would be installed if I install `f5-tts-mlx` but it seems like I have to install them one by one manually.

**Comment by ahmetkca** [comment]
@lucasnewman what's your machine? I am having problems with torchaudio. There is no available backend to process the reference audio file.

**Comment by lucasnewman** [comment]
Try `pip install -U f5-tts-mlx` and see if you're still having issues. I replaced the torchaudio dependency with soundfile which others seemed to be using more easily.

**Comment by lucasnewman** [comment]
Also give the script invocation a shot! See the readme for more details.
