### ISSUE TITLE
Does it support streaming?

### ISSUE THREAD

**Issue by AlexCheema** [lucasnewman/f5-tts-mlx#20]
Hey, this is awesome!

I'm looking for a TTS solution that can run in realtime on M3 Pro.
Can this stream generate the audio?

**Comment by lucasnewman** [comment]
No, it's not an autoregressive model, so it's not possible to stream. There are some tips here to generate as quickly as possible, though: https://github.com/lucasnewman/f5-tts-mlx/issues/16
