### ISSUE TITLE
Using reference audio doesn't work properly

### ISSUE THREAD

**Issue by tanmay1100** [lucasnewman/f5-tts-mlx#23]
When using reference audio, the audio that is output is 0.04 seconds long every single time, it cuts off as soon as the first letter is pronounced.

**Comment by lucasnewman** [comment]
Are you specifying duration explicitly or using the duration predictor? Sounds like the duration settings isn't being set correctly. If you have a command line innovation that reproduces this, I can look.

**Comment by tanmay1100** [comment]
python -m f5_tts_mlx.generate \
--text "The quick brown fox jumped over the lazy dog."
--ref-audio /path/to/audio.wav
--ref-text "This is the caption for the reference audio."

I am using this command, not setting the duration explicitly

**Comment by tanmay1100** [comment]
idk what changed, but it works now
