### ISSUE TITLE
fyi: I created a fork to do some blog post

### ISSUE THREAD

**Issue by tikikun** [lucasnewman/f5-tts-mlx#26]
Hi Lucas, just to be transparent I created a fork of your repo and add some details regarding quantization in my blog post at
https://github.com/tikikun/f5-tts-mlx-quantized
The blog post:https://alandao.net/posts/ultra-compact-text-to-speech-a-quantized-f5tts/
This is just a personal blog post and has no other incentives. I just want to emphasize that here since my modified part is minimal (and probably also is adhoc to the post only). I also gave proper appreciation for your work on this repo.

Since I might not be maintaining the code for long after the blog post so I don't have plan to open a PR to contribute back (and my code probably is not that good), but feel free to check out my small trick to quantize f5tts if you prefer in the blog post.

Thank you for your amazing work on f5-tts-mlx I really, really like it!

**Comment by hahuyhoang411** [comment]
Wow cool blogpost indeed

**Comment by lucasnewman** [comment]
Super cool! I love it!

**Comment by lucasnewman** [comment]
I just went ahead and added this so you don't have to maintain your fork. Thanks for the contribution!

**Comment by tikikun** [comment]
thank you again for the cool project <3
