### ISSUE TITLE
How to train duration predictor with custom dataset

### ISSUE THREAD

**Issue by hungpv297** [lucasnewman/f5-tts-mlx#27]
Thanks for your impressive work!

I have a question.
How can I finetune a duration predictor model for my custom dataset?

Thank in advance!

**Comment by eamag** [comment]
I think you can, take a look at duration_trainer.py https://github.com/lucasnewman/f5-tts-mlx/blob/9541e7ca772582b486da4d8cb0b3a460da261096/f5_tts_mlx/duration_trainer.py#L62


I assume it uses the same libritts dataset? https://github.com/lucasnewman/f5-tts-mlx/blob/9541e7ca772582b486da4d8cb0b3a460da261096/f5_tts_mlx/data.py#L169

**Comment by lucasnewman** [comment]
Take a look at https://github.com/lucasnewman/f5-tts-mlx/issues/17 where I provided the training code and dataset details.
