### ISSUE TITLE
Any chance duration could be made optional?

### ISSUE THREAD

**Issue by simonw** [lucasnewman/f5-tts-mlx#5]
It's frustrating having to guess the ideal length of the clip before generating it. Is it at all possible to automatically derive a sensible duration from the length of the input text?

Even a rough estimate would still be better than having to guess each time.

**Comment by simonw** [comment]
Looks like this is code in the original repo for estimating duration:

https://github.com/SWivid/F5-TTS/blob/0297be2541f9a062f9d54103926bdb88d63440ea/inference-cli.py#L270-L275

**Comment by lucasnewman** [comment]
Yep, an optimal solution would just be a duration predictor like Voicebox/E2-TTS, which is what I'm working on adding. That heuristic seems a little dodgy but better than nothing I suppose 😅

**Comment by lucasnewman** [comment]
@simonw Try the latest, which has the same heuristic in place and makes duration optional.
