### ISSUE TITLE
ValueError: Invalid high padding size (-2966919) passed to pad for axis 1. Padding sizes must be non-negative

### ISSUE THREAD

**Issue by yolossn** [lucasnewman/f5-tts-mlx#6]
Tried running the generate example with a sample audio and getting the following error.

```bash
 python -m f5_tts_mlx.generate \
--text "The quick brown fox jumped over the lazy dog." \
--ref-audio ~/Desktop/demo.wav \
--ref-text "..."
```

Error:
> Fetching 2 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 23763.76it/s]
Got reference audio with duration: 123.79 seconds
Building prefix dict from the default dictionary ...
Loading model from cache /var/folders/yh/lp0w16rj7ng0zww1_ccqnykm0000gn/T/jieba.cache
Loading model cost 0.308 seconds.
Prefix dict has been built successfully.
Using duration of 3.25 seconds for generated speech.
Generating 11910 total frames of audio...
Fetching 2 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 19195.90it/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/username/git/random/f5-tts-mlx/f5_tts_mlx/generate.py", line 168, in <module>
    generate(
  File "/Users/username/git/random/f5-tts-mlx/f5_tts_mlx/generate.py", line 82, in generate
    wave, _ = f5tts.sample(
              ^^^^^^^^^^^^^
  File "/Users/username/git/random/f5-tts-mlx/f5_tts_mlx/cfm.py", line 372, in sample
    cond = mx.pad(cond, [(0, 0), (0, max_duration - cond_seq_len), (0, 0)])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid high padding size (-2966919) passed to pad for axis 1. Padding sizes must be non-negative

**Comment by mobile-appz** [comment]
> Tried running the generate example with a sample audio and getting the following error.
> 
> ```shell
>  python -m f5_tts_mlx.generate \
> --text "The quick brown fox jumped over the lazy dog." \
> --ref-audio ~/Desktop/demo.wav \
> --ref-text "..."
> ```
> 
> Error:
> 
> > Fetching 2 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 23763.76it/s]
> > Got reference audio with duration: 123.79 seconds
> > Building prefix dict from the default dictionary ...
> > Loading model from cache /var/folders/yh/lp0w16rj7ng0zww1_ccqnykm0000gn/T/jieba.cache
> > Loading model cost 0.308 seconds.
> > Prefix dict has been built successfully.
> > Using duration of 3.25 seconds for generated speech.
> > Generating 11910 total frames of audio...
> > Fetching 2 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 19195.90it/s]
> > Traceback (most recent call last):
> > File "", line 198, in _run_module_as_main
> > File "", line 88, in _run_code
> > File "/Users/username/git/random/f5-tts-mlx/f5_tts_mlx/generate.py", line 168, in 
> > generate(
> > File "/Users/username/git/random/f5-tts-mlx/f5_tts_mlx/generate.py", line 82, in generate
> > wave, _ = f5tts.sample(
> > ^^^^^^^^^^^^^
> > File "/Users/username/git/random/f5-tts-mlx/f5_tts_mlx/cfm.py", line 372, in sample
> > cond = mx.pad(cond, [(0, 0), (0, max_duration - cond_seq_len), (0, 0)])
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > ValueError: Invalid high padding size (-2966919) passed to pad for axis 1. Padding sizes must be non-negative

I'm getting the same error

**Comment by lucasnewman** [comment]
Your reference audio should be mono @ 24kHz and should be 10 seconds at most. Looks like you're using a ~2 min sample — give it a try with a shorter sample.

**Comment by mobile-appz** [comment]
> Your reference audio should be mono @ 24kHz and should be 10 seconds at most. Looks like you're using a ~2 min sample — give it a try with a shorter sample.

I experienced this bug with stereo audio files regardless of duration. I found the solution was to use a mono reference audio file. @yolossn
