### ISSUE TITLE
fine-tuning/training the model

### ISSUE THREAD

**Issue by taalua** [lucasnewman/f5-tts-mlx#9]
Thank you for the wonderful work. Is it possible to fine-tuning or training this implementation with the duration model?

**Comment by lucasnewman** [comment]
Yes, it's definitely possible. I added a trainer for the duration predictor model (not yet used), but it's relatively straightforward to adapt it to train the speech model as well. I'll see if I can add a trainer for it some time this week.

As a note, the model takes a _lot_ of compute and a fair amount of data to train, so if you're hoping to e.g. transfer to a new language it would probably be more efficient to train a Pytorch model that you can run on an H100 or something like that. If you're just trying to tune the voice matching, I think it should be fine to train it on your M-series machine.

**Comment by lucasnewman** [comment]
Ok, if you update to the latest you should be able to do something like this to fine-tune the existing model:

```python
import mlx.core as mx
from mlx.utils import tree_flatten

from f5_tts_mlx.cfm import F5TTS
from f5_tts_mlx.trainer import F5TTSTrainer
from f5_tts_mlx.data import load_libritts_r


f5tts = F5TTS.from_pretrained("lucasnewman/f5-tts-mlx")

num_trainable_params = sum([p[1].size for p in tree_flatten(f5tts.trainable_parameters())])
print(f"Using {num_trainable_params:,} trainable parameters.")

batch_size = 2
max_duration = 5
dataset = load_libritts_r(split="dev-clean", max_duration=max_duration)

trainer = F5TTSTrainer(model=f5tts, num_warmup_steps=1000, max_grad_norm=1, log_with_wandb=False)
trainer.train(
    train_dataset=dataset,
    learning_rate=1e-4,
    log_every=10,
    total_steps=100_000,
    batch_size=batch_size
)
```

You'll need to adjust the hyperparams to fit your setup.

**Comment by taalua** [comment]
thank you.
